### ISSUE TITLE
Extension Fails on Mac OS

### ISSUE THREAD

**Issue by spillsthrills** [uctakeoff/vscode-counter#36]
Latest version on Mac OS Latest.

[2020-09-03 11:42:05.070] [renderer1] [error] command failed with error code 2: error parsing glob '!/{**/.gitignore,**/.vscode/**,**/node_modules/**,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter}': nested alternate groups are not allowed
: Error: command failed with error code 2: error parsing glob '!/{**/.gitignore,**/.vscode/**,**/node_modules/**,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter}': nested alternate groups are not allowed

    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5072:889)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5152:906
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5151:8
[2020-09-03 11:42:55.330] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-09-03 11:42:55.331] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-09-03 11:43:00.333] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-09-03 11:43:00.333] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-09-03 11:43:05.896] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-09-03 11:43:05.973] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-09-03 11:44:24.672] [renderer1] [error] command failed with error code 2: error parsing glob '!/{**/.gitignore,**/.vscode/**,**/node_modules/**,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter}': nested alternate groups are not allowed
: Error: command failed with error code 2: error parsing glob '!/{**/.gitignore,**/.vscode/**,**/node_modules/**,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter}': nested alternate groups are not allowed

    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5072:889)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5152:906
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5151:8
[2020-09-03 11:46:41.734] [renderer1] [error] command failed with error code 2: error parsing glob '!/{**/.gitignore,**/.vscode/**,**/node_modules/**,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter}': nested alternate groups are not allowed
: Error: command failed with error code 2: error parsing glob '!/{**/.gitignore,**/.vscode/**,**/node_modules/**,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/*.js: { "when": "$(basename).ts" },.VSCodeCounter}': nested alternate groups are not allowed

    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5072:889)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5152:906
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5151:8

**Comment by uctakeoff** [comment]
I'm sorry.
The error message is not from VSCodeCounter, so I don't know what's going on.

This article may help you.
https://github.com/Microsoft/vscode/issues/32761
